using System;
using System.Collections.Generic;
using UnityEngine;

namespace Mod
{
    public class MainModClass
    {
        public static void Main()
        {
            ModAPI.Register(
    new Modification()
    {
        OriginalItem = ModAPI.FindSpawnable("Human"), //We basically derive from an already existing item in the game to create a new on...in this case we have a human...
        NameOverride = "Custom Human 1", // the name of the custom Human...
        NameToOrderByOverride = "Custom Human 1", //0 comes before 1 one as an example and Custom Human 1 would come befor the Human in the Menu because c is before h in´the alphabet...
        DescriptionOverride = "This is a custom description to a custom Human...", //Explains itself, a simple description of your Human / Item / ect......
        CategoryOverride = ModAPI.FindCategory("Entities"), // This is the Category in which our Human should appear in...
        ThumbnailOverride = ModAPI.LoadSprite("Textures/CustomHuman1Thumbnail.png"), //The Thumbnail...
        AfterSpawn = (Instance) =>
        {
            var skin = ModAPI.LoadTexture("Textures/CustomHuman1Skin.png"); //The Skin texture for the Human...
            var flesh = ModAPI.LoadTexture("Textures/CustomHuman1Flesh.png"); //The Flesh texture for the Human...
            var bone = ModAPI.LoadTexture("Textures/CustomHuman1Bone.png"); //The Bone texture for the Human...

            var person = Instance.GetComponent<PersonBehaviour>(); // this gets the personbehaviour component of the Human we want to modify...

            person.SetBodyTextures(skin, flesh, bone, 1); //This sets the textures of our custom Human to the our own, instead of just the normal ones...The last value or the 1 has something to do with the texture size or so...

            person.SetBruiseColor(178, 0, 178); //Here we set the R.G.B (Red, Green, Blue) values for our bruises -> this would be purple like color...
            person.SetSecondBruiseColor(154, 0, 7);
            person.SetThirdBruiseColor(207, 206, 120);
            person.SetRottenColour(202, 199, 104);
            person.SetBloodColour(108, 0, 4); // this doesn't set the Liquid color of the human blood...if we want to change the blood type or color however, we musst then create our own "liquid"...,which I will show in a later Tutorial...
        }
    }
);
        }
    }
}